"""Add amenities table and listing amenities table.

Revision ID: dfb51a18a3ee
Revises: 01f7cbb4c555
Create Date: 2026-02-08 14:35:25.615765

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dfb51a18a3ee"
down_revision: Union[str, Sequence[str], None] = "01f7cbb4c555"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "amenities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False, comment="Stable identifier"),
        sa.Column(
            "label", sa.Text(), nullable=False, comment="Human-readable amenity name"
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", name="uq_amenity_key"),
    )
    op.create_index(op.f("ix_amenities_key"), "amenities", ["key"], unique=True)
    op.create_table(
        "listing_amenities",
        sa.Column("listing_id", sa.UUID(), nullable=False),
        sa.Column("amenity_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["amenity_id"], ["amenities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["listing_id"], ["listings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("listing_id", "amenity_id"),
    )
    op.create_unique_constraint(
        "uq_listing_amenity", "listing_amenities", ["listing_id", "amenity_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_listing_amenity", "listing_amenities", type_="unique")
    op.drop_table("listing_amenities")
    op.drop_index(op.f("ix_amenities_key"), table_name="amenities")
    op.drop_table("amenities")
    # ### end Alembic commands ###
