"""Add owner_id to listings and properties tables.

Revision ID: aadb6c07d39b
Revises: 124bfb40c34d
Create Date: 2026-02-23 16:28:59.135277

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aadb6c07d39b"
down_revision: Union[str, Sequence[str], None] = "124bfb40c34d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "listings",
        sa.Column(
            "owner_id",
            sa.String(),
            nullable=False,
            comment="User ID of the listing owner",
        ),
    )
    op.drop_constraint(op.f("listings_user_id_fkey"), "listings", type_="foreignkey")
    op.create_foreign_key(
        None, "listings", "users", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("listings", "user_id")
    op.add_column(
        "properties",
        sa.Column(
            "owner_id",
            sa.String(),
            nullable=False,
            comment="User ID of the property owner",
        ),
    )
    op.create_foreign_key(
        None, "properties", "users", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "properties", type_="foreignkey")
    op.drop_column("properties", "owner_id")
    op.add_column(
        "listings",
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "listings", type_="foreignkey")
    op.create_foreign_key(
        op.f("listings_user_id_fkey"),
        "listings",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("listings", "owner_id")
    # ### end Alembic commands ###
