"""Add listings table.

Revision ID: 01f7cbb4c555
Revises: 0eedd04c8376
Create Date: 2026-02-08 14:14:25.127294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01f7cbb4c555'
down_revision: Union[str, Sequence[str], None] = '0eedd04c8376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('monthly_rent', sa.Integer(), nullable=False),
    sa.Column('deposit_amount', sa.Integer(), nullable=True),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('lease_term_months', sa.Integer(), nullable=True),
    sa.Column('lease_type', sa.String(), nullable=True),
    sa.Column('unit_type', sa.Enum('STUDIO', 'ONE_B_ONE_B', 'TWO_B_TWO_B', 'SHARED_ROOM', 'PRIVATE_ROOM', 'OTHER', name='unittype'), nullable=False),
    sa.Column('square_feet', sa.Integer(), nullable=True),
    sa.Column('max_occupants', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'RENTED', 'ARCHIVED', name='listingstatus'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listings')
    # ### end Alembic commands ###
